<a href="https://colab.research.google.com/github/nittasamith/IIY-IIIS-PYTHON/blob/PythonNumpy/PythonNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([3,2,1])
print("\n2.Array:")
print("Array a:",a)
print("Array b:",b)


2.Array:
Array a: [1 2 3]
Array b: [3 2 1]


In [ ]:
c = np.add(a,b)
print("\n3.Addition of a and b:",c)


3.Addition of a and b: [4 4 4]


In [ ]:
print("\n4. Check if all the elements in array a are non-zero:",np.all(a))


4. Check if all the elements in array a are non-zero: True


In [ ]:
zeros_arr = np.zeros((2,3))
print("\n11.Array of zeros:\n",zeros_arr)


11.Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_arr = np.ones((2,3))
print("\n12.Array of ones:\n",ones_arr)


12.Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
lin_arr = np.linspace(0,1,5)
print("\n13. Evenly spaced numbers from 0 to 1 (5 values):", lin_arr)


13. Evenly spaced numbers from 0 to 1 (5 values): [0.   0.25 0.5  0.75 1.  ]


In [ ]:
list_from_array = lin_arr.tolist()
print("\n14. Convert linspace array to list :",list_from_array)


14. Convert linspace array to list : [0.0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
import numpy as np
arr = np.array([3,7,1,9,3,7,5,1,9,3])
num = 5
matrix = np.array([[10,50,30],
                  [40,20,60],
                  [70,80,90]])
max_val = np.max(matrix)
min_val = np.min(matrix)
max_idx = np.argmax(matrix)
min_idx = np.argmin (matrix)


print("\nCount of elements:",arr.size)
print("\nUnique values:",np.unique(arr))
print("\n Bincount (frequency of each number):",np.bincount(arr))


Count of elements: 10

Unique values: [1 3 5 7 9]

 Bincount (frequency of each number): [0 2 0 3 0 1 0 2 0 2]


In [ ]:
import numpy as np
print("a. Help on np.add function:\n")
help(np.add)

a. Help on np.add function:

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `

In [ ]:
arr2 = np.array([1,3,2,5])
arr3 = np.array([1,2,3,4])
print("\nc.Element-wise comparison:")
print("Array 1:",arr2)
print("Array 2:",arr3)


c.Element-wise comparison:
Array 1: [1 3 2 5]
Array 2: [1 2 3 4]


In [ ]:
print("Greater (arr2 > arr3):",np.greater(arr2,arr3))
print("Greater Equal (arr2 >= arr3):",np.greater_equal(arr2,arr3))
print("Less (arr2 < arr3):",np.less(arr2,arr3))
print("Less Equal (arr2 <= arr3):",np.less_equal(arr2,arr3))
print("Equal (arr2 == arr3):",np.equal(arr2,arr3))

Greater (arr2 > arr3): [False  True False  True]
Greater Equal (arr2 >= arr3): [ True  True False  True]
Less (arr2 < arr3): [False False  True False]
Less Equal (arr2 <= arr3): [ True False  True False]
Equal (arr2 == arr3): [ True False False False]
